version: '3'
services:
  backend:
    container_name: backend
    restart: always
    build: backend
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - rede
  frontend:
    container_name: frontend
    restart: always
    build: frontend
    ports:
      - "4200:4200"
    networks:
      - rede
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    networks:
      - rede
networks:
  rede:
    driver: "bridge"