version: '3'
services:
  frontend:
    container_name: frontend
    restart: always
    build: .\frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - rede
  backend:
    container_name: backend
    restart: always
    build: .\backend
    ports: 
     - "3000:3000"
    depends_on:
      - mongo
    networks:
      - rede
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin mongo   
    ports:
      - "27017:27017"
    networks:
      - rede
networks:
  rede:
    driver: "bridge"