version: '3'
services:
  backend:
    image: back
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - rede
  frontend:
    image: front
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "4200:4200"
    networks:
      - rede
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    networks:
      - rede
networks:
  rede:
    driver: "bridge"